### ISSUE TITLE
Incorrect slider calculation

### ISSUE THREAD

**Issue by YaLTeR** [smoogipoo/osu-BMAPI#1]
A simple beatmap with a couple of circles and a Bezier slider, the slider end time is calculated improperly. Also tried to output the PositionAtTime-s at different times (100, 200, 300 and 400) and got incorrect info (for the first two - huge negative coordinates, for others - not matching with Auto at those times).

Code: https://gist.github.com/YaLTeR/f6927610792a11a66ae2
Log it output for that map and an Auto replay of that map: https://gist.github.com/YaLTeR/483a9d71c9d8f11a8e7d

**Comment by minisbett** [comment]
Could you tryna fix that? lmao

**Comment by smoogipoo** [comment]
This library is deprecated. You should be using https://github.com/ppy/osu instead.

Here's an example: https://github.com/ppy/osu-tools/blob/6be672dd0770757cafa5a542961aa1c1fb821077/PerformanceCalculator/Difficulty/DifficultyCommand.cs#L49

It is available as a nuget package: https://www.nuget.org/packages/ppy.osu.Game/
